### PR TITLE
Check for diffBranch existence before fetch files

### LINKED ISSUE #114: fetchGitDiff runs error when the diffBranch is not existed
Firstly I create a new repo, it has no branches.  
Then, I push codes which are already commited from local on branch `master` to initial the repo.
But there comes the error:
```
fatal: ambiguous argument 'origin/master...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
This error also occurs when baseBranch setted in userConfig is not existed. 
So, maybe there should be some ways to skip `git diff` in this event?

### PR DESCRIPTION
**Pull request by WhiteYin**
This PR introduces a check to see if the diffBranch is existed. If not, lint all tracked files instead of fetch from origin branch or baseBranch.

Closes #114

### CODE REVIEW

**Comment by theenadayalank** [comment]
Thank you @WhiteYin  for taking the time to make this change. It has been a long time pending item that I have skipped for months. I'm really glad that you made this change.

File: index.js [hunk 1]
```diff
@@ -91,19 +94,42 @@ if (process.stdout.isTTY) {
...
-  let committedGitFiles = [];
-
+  let isdiffBranchExisted = false;
   try {
-    committedGitFiles = fetchGitDiff(diffBranch);
-    debug('Committed GIT files: ', committedGitFiles);
-  }
-  catch(err) {
+    isdiffBranchExisted = checkForBranchExistence(baseBranch,remote);
+    debug('Check whether branch is existed: ', diffBranch);
```
Comment (theenadayalank) [inline index.js:100]: This PR is good to go with a success log stating that the base branch is existing.

Comment (theenadayalank) [reply index.js:100]: It would make the debugging process a bit easier.

**Comment by theenadayalank** [comment]
I apologize for the delay in the reviewing this PR.

File: index.js (hunk 1 above)
Comment (WhiteYin) [reply index.js:100]: How about now? 😊

Comment (theenadayalank) [reply index.js:100]: Cool 👍

File: index.js [hunk 2]
```diff
@@ -107,6 +107,7 @@ if (process.stdout.isTTY) {
 
   let committedGitFiles = [];
   if (isdiffBranchExisted) {
+    log(success('Great, we find the ' + diffBranch + ' branch.'));
```
Comment (theenadayalank) [inline index.js:110]: Unfortunately, I have merged this PR without noticing this line. I meant to add the log in debug mode. It's my fault that I didn't communicate well. I'm sorry for the inconvenience.

If you don't mind, could you raise another PR with a log message which prints only in debug mode?

If the base branch is found, you can put a log in debug mode. (something like `Base branch exists`)
If not found, a log can be printed in normal mode. (something like below)

⚠️`The base branch(branch_name) doesn't exist`
`Hence all files will be processed`

Comment (WhiteYin) [reply index.js:110]: Well,that's my fault.I will fix it later.
